#!/bin/sh

MODE="$1"
HOST="$2"
SESS="$3"

SSHARGS=( "ssh" "-t" "${HOST}" )

case "${MODE}" in
    screen) exec ${SSHARGS[@]} screen -U -RR -D "${SESS}"
            ;;
    tmux)   test -n "${SESS}" \
              && exec ${SSHARGS[@]} "tmux attach -t '${SESS}' || tmux new -s '${SESS}'" \
              || exec ${SSHARGS[@]} "tmux attach || tmux new"
            ;;
    *)      echo "$0: ${MODE} is not a known mode" >&2
            exit 1
esac
