#!/usr/bin/env python

# datauri --type --base64 [file]

import sys
import base64
import optparse

p = optparse.OptionParser()
p.add_option('--type', '-t')
p.add_option('--base64', '-b', action='store_true')

def transform(f, infile, out):
    while True:
        chunk = infile.read(4096)
        if not chunk:
            break
        chunk = f(chunk) if f else chunk
        out.write(chunk)

def main(argv=sys.argv[1:]):
    opts, args = p.parse_args(argv)
    infile, out = sys.stdin, sys.stdout
    # TODO args
    out.write('data:')
    if opts.type:
        out.write(str(opts.type) + ";")
    if opts.base64:
        out.write("base64,")
        transform(base64.b64encode, infile, out)
    else:
        out.write(",")
        transform(None, infile, out)
    out.write('\n')

if __name__ == "__main__":
    main()
