#!/bin/sh
D=$HOME/devel/binutils/flake8env
PV=3.9
PYSTDLIB="/usr/local/$(readlink /usr/local/bin/python3 | cut -d / -f 2-4)/Frameworks/Python.framework/Versions/$PV/lib/python$PV"
[ ! -d "$PYSTDLIB" ] && echo "$0: stdlib is gone, upgraded python?" && exit 123
export PYTHONPATH=$D/lib/python$PV/site-packages:$PYSTDLIB
exec $D/bin/python -SBsm flake8 "$@"
