#!/bin/sh
D=$HOME/devel/binutils/flake8env
PV=3.10
PYSTDLIB="$HOME/.pyenv/versions/3.10.6/lib/python$PV"
[ ! -d "$PYSTDLIB" ] && echo "$0: stdlib is gone, upgraded python?" && exit 123
export PYTHONPATH=$D/lib/python$PV/site-packages:$PYSTDLIB
exec $D/bin/python -SBsm flake8 "$@"
