#!/bin/sh

# git-flake8: run flake8 on Python files that have been changed or aren't added

PYTHON="/usr/bin/env python"
exec git ls-files --modified --others --exclude-standard -z '*.py' | xargs -0 "$PYTHON" -m flake8
