#!/usr/bin/env python
"Like tail -f and grep -c!"

import os
import sys
import time

interval = 1.0

def greprate(f, grep):
    t0 = time.time()
    while True:
        time.sleep(interval)
        chunk = os.read(f.fileno(), 1<<20)
        t1 = time.time()
        print chunk.count(grep) / (t1 - t0), 'matches/second'
        t0 = t1

def main(args=sys.argv[1:]):
    grep, fn = args

    if fn == '-':
        greprate(sys.stdin, grep)
    else:
        with open(fn) as f:
            f.seek(0, 2)
            greprate(f, grep)

if __name__ == "__main__":
    main()
