#!/usr/bin/env python
"Like tail -f and grep -c!"

import os
import sys
import time

interval = 1.0

def main(args=sys.argv[1:]):
    grep, fn = args
    with open(fn) as f:
        f.seek(0, 2)
        while True:
            chunk = os.read(f.fileno(), 1<<20)
            time.sleep(interval)
            print chunk.count(grep) / interval, 'matches/second'

if __name__ == "__main__":
    main()
