#!/usr/bin/env python2

import os
import sys
import argparse
import SimpleHTTPServer


p = argparse.ArgumentParser()
p.add_argument('--port', '-p', type=int, default=8000)
p.add_argument('directory', nargs='?', default='.')


if __name__ == "__main__":
    args = p.parse_args()
    sys.argv[1:] = [str(args.port)]
    os.chdir(args.directory)
    SimpleHTTPServer.test()
