#!/usr/bin/env python

import os
import sys
import SimpleHTTPServer

if __name__ == "__main__":
    if len(sys.argv) > 1:
        wd, sys.argv[1:] = sys.argv[1], sys.argv[2:]
        os.chdir(wd)
    SimpleHTTPServer.test()
