#!/usr/bin/env python

import sys
import datetime

def filter_scheduled(it, prefix="Scheduled: "):
    for line in it:
        if line.startswith(prefix):
            yield line[len(prefix):]

def parse_datetimes(line):
    lead, start_txt, to, stop_txt = line.strip().rsplit(' ', 3)
    start = datetime.datetime.strptime(start_txt, "%H:%M:%S")
    stop = datetime.datetime.strptime(stop_txt, "%H:%M:%S")
    stop = start.replace(hour=stop.hour, minute=stop.minute, second=stop.second)
    return start, stop

def main(args=sys.argv[1:]):
    for line in filter_scheduled(sys.stdin):
        start, stop = parse_datetimes(line)
        delta = stop - start
        print '{hours:d}h{minutes:02d}m'.format(hours=(delta.seconds // 3600),
                                          minutes=((delta.seconds % 3600) / 60))

if __name__ == "__main__":
    main()
