#!/bin/bash

TGT=$(python <<PY
import random, string
print "".join(random.choice(string.letters + string.digits) for i in xrange(12))
PY
).png

TGT="${1:-$TGT}"

LSRC=/tmp/$TGT
DST=jing/$TGT
URL=http://bsg.lericson.se/jing/$TGT

pbpastim png > "$LSRC" || exit
scp -q "$LSRC" "${HOST:-moln.lericson.se}:htdocs/$DST" || exit
rm "$LSRC"
echo "$URL"
