#!/bin/bash

TGT=$(randname).png
TGT="${1:-$TGT}"

LSRC=/tmp/$TGT
DST=jing/$TGT
URL=https://bsg.lericson.se/jing/$TGT

screencapture -i "$LSRC" || exit
scp -q "$LSRC" "${HOST:-moln.lericson.se}:htdocs/$DST" || exit
rm "$LSRC"
echo "$URL"
