#!/bin/bash
set -e
out="$1"
shift
while when_changed "$@"; do
  if make $out </dev/null; then
    terminal-notifier -group makeloop$$ -title "$out" -message "Build Finished" -sound Bottle
  else
    terminal-notifier -group makeloop$$ -title "$out" -message "Build Failed: '$?'" -sound Sosumi
  fi
done
