#!/bin/sh

# usage: pbedit [args]
# edit the pasteboard text buffer
# any and all arguments are passed to pbpaste/pbcopy

FN=`mktemp pbedit.XXXXXXX`
trap "rm $FN" EXIT
pbpastim "$@" >$FN || exit 1
"${EDITOR:-vim}" "$FN" || exit 1
exec pbcopim <$FN
