#!/usr/bin/env python3

import sys
import pydoc


def which(spec):
    obj, name = pydoc.resolve(spec)
    filename, lineno = None, None

    if hasattr(obj, '__func__'):
        obj = obj.__func__

    if hasattr(obj, '__code__'):
        obj = obj.__code__

    if hasattr(obj, 'co_firstlineno'):
        lineno = obj.co_firstlineno

    if hasattr(obj, 'co_filename'):
        filename = obj.co_filename
    elif hasattr(obj, '__file__'):
        filename = obj.__file__
    else:
        raise FileNotFoundError(spec)

    return filename, lineno


def main(args=sys.argv[1:]):
    for arg in sys.argv[1:]:
        filename, lineno = which(arg)
        print(filename)


if __name__ == "__main__":
    main()
