#!/usr/bin/env python
"random-file <dir1 ...> -- pick a random file in a directory"

import os
import sys
import random

nondotfile = lambda f: not f.startswith('.')

if __name__ == "__main__":
    for d in sys.argv[1:]:
        print os.path.join(d, random.choice(filter(nondotfile, os.listdir(d))))
