#!/usr/bin/env python

import sys
import string

t = string.maketrans(string.ascii_lowercase + string.ascii_uppercase,
                     string.ascii_lowercase[13:] + string.ascii_lowercase[:13] +
                     string.ascii_uppercase[13:] + string.ascii_uppercase[:13])

def main(args=sys.argv[1:]):
    if not args:
        text = sys.stdin.read()
    else:
        text = ' '.join(args) + '\n'
    sys.stdout.write(text.translate(t))

if __name__ == "__main__":
    main()
