#!/bin/bash

LOCAL_HOST="${LOCAL_HOST:-127.0.0.1:2525}"
SMTP_HOST="${SMTP_HOST:-mailout.comhem.se:25}"
TUNNEL_HOST="${1:-${TUNNEL_HOST:-lericson.se}}"

CMD=( ssh -fNL "${LOCAL_HOST}:${SMTP_HOST}" "$TUNNEL_HOST" )
TUNPID="$(pgrep -f "${CMD[*]}")"
RC="$?"

if [ "$RC" -ne 0 ]; then
  echo "$0: setting up tunnel"
  echo "${CMD[@]}"
  exec "${CMD[@]}"
else
  echo "$0: tunnel seems to be up at $TUNPID"
fi
