#!/usr/bin/env python
"""tee but for pty

teety ls -l >a.ttydata
"""


from __future__ import print_function

import os
import sys
import pty
import select
import subprocess


def main(args=sys.argv[1:]):
    mo, so = pty.openpty()
    p = subprocess.Popen(args, stdin=sys.stdin, stdout=so, stderr=so, close_fds=True)
    r = os.read(mo, 4096)
    os.close(so)
    while r:
        if not r:
            break
        os.write(sys.stdout.fileno(), r)
        r = os.read(mo, 4096)
    sys.exit(p.wait())

if __name__ == "__main__":
    main()
