#!/usr/bin/env python

import sys
from appscript import app, its, k

Things = app("Things")

status_map = {k.completed:  "x",
              k.canceled:   "c",
              k.open:       " "}

def parse_list_ref(v):
    if v.startswith("proj="):
        return Things.projects[v[5:]]
    elif v.startswith("area="):
        return Things.areas[v[5:]]
    return Things.lists[v]

def print_todos(to_dos):
    names = list(to_dos.name.get())
    statuses = list(to_dos.status.get())

    for (name, status) in zip(names, statuses):
        marker = status_map.get(status, "?")
        print (u"[%s] %s" % (marker, name)).encode("utf-8")

list_names = map(unicode, sys.argv[1:])

if not list_names:
    sel = Things.selected_to_dos
    if not sel.count():
        sel = Things.lists.ID("FocusToday").to_dos
    print_todos(sel)
else:
    for list_name in list_names:
        lst = parse_list_ref(list_name)
        if len(list_names) > 1:
            print (u"### %s" % (lst.name.get(),)).encode("utf-8")
        print_todos(lst.to_dos)
