#!/usr/bin/env python3
import sys
import json
import subprocess

err, inp  = subprocess.getstatusoutput('tmutil status | tail +2 | plutil -convert json -o - -')
if err != 0:
    raise ValueError(err)
d = json.loads(inp)

if int(d['Running']) == 0:
    print("Time Machine is idle.")
elif 'Progress' not in d:
    print(f"Time Machine is active ({d['BackupPhase']})")
else:
    if 'TimeRemaining' in d['Progress']:
        print(f"Time remaining:   {int(d['Progress']['TimeRemaining'])/3600.:.2f} hours")
    print(f"Copied bytes: {int(d['Progress']['bytes'])/1024/1024.:-10.2f} MiB")
    print(f"Total  bytes: {int(d['Progress']['totalBytes'])/1024/1024.:-10.2f} MiB")
if int(d.get('Stopping', 0)) == 1:
    print("Time Machine is stopping.")
