#!/usr/bin/env python3
"read all objects in a pickle file"

import sys
import pickle
from pprint import pprint


def main(args=sys.argv[1:]):
    for arg in args:
        with open(arg, 'rb') as fp:
            while True:
                try:
                    obj = pickle.load(fp)
                except EOFError:
                    break
                else:
                    pprint(obj)


if __name__ == "__main__":
    main()
