#!/usr/bin/env python

import sys
import random

def unsort(fp):
  L = fp.readlines()
  random.shuffle(L)
  sys.stdout.write(''.join(L))

def main(args=sys.argv[1:]):
  if not args:
    unsort(sys.stdin)
  else:
    for fn in args:
      with open(fn) as fp:
        unsort(fp)

if __name__ == "__main__":
  main()
