#!/usr/bin/env python3
"open vi-like editor on a python name"

import os
import sys
import pydoc

args = [os.environ.get('EDITOR', 'vim')]

for arg in sys.argv[1:]:
    obj, name = pydoc.resolve(arg)

    if hasattr(obj, '__func__'):
        obj = obj.__func__

    if hasattr(obj, '__code__'):
        obj = obj.__code__

    if len(args) == 1 and hasattr(obj, 'co_firstlineno'):
        args.append(f'+{obj.co_firstlineno}')

    if hasattr(obj, 'co_filename'):
        args.append(obj.co_filename)
    elif hasattr(obj, '__file__'):
        args.append(obj.__file__)
    else:
        print('could not find filename for', arg, file=sys.stderr)
        sys.exit(1)

os.execvp(args[0], args)
